import base64
from typing import List
# from fastapi_jwt_auth import AuthJWT
# from pydantic import BaseModel

from config import settings

JWT_PRIVATE_KEY="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWFFJQkFBS0JnUUNyYk1xbTFDd1RhcVh6cTVkUVNjQkFOdzNIbkpZYWxISm5zM2x2d041dVVHc1dRa3NYCjBQWnJOZDdVSVJQZDRZRldDUW9rTyt5dndTTitEZ2lrdmRTTk91ek12ZUtHOXhrOTYrbUFHUHlMM1U3SjVtTVgKVEcvZEMvbGh0Tmo1S01rZWRhS2h6cTBFTHZha0RlTVF2ejhBWmk2NDUzeDl6TWdjY2RsQ0RpdVNFd0lEQVFBQgpBb0dBVE9kMGpwMVczS3NXb2hkVHZiQW9jR2FDWncrSGc0c2ZQQWlYTFJ4d2JUcmtuOHJEMTM1bVhqaC9xOWpmCkNjWjErSHY3c2IrMGNqQ0tWSzNGRU9zY3BEU1hET3MveDJrRk04NnlmRmppdVh6ZDVJSkFlY2lOclBiejk1WkUKRlRqQXZQb25YTU1lVWc5VGFVRkhOU0VSeVRNWER2N1RXa1FZejk1UjZtVVA1UUVDUVFENG0wb0ZMUDgvenkzTAo4cnhDTzJJc2cvQTY0SzZ0VitObkYzOVYrQThWT2ZOYmlSbUY2NUx4RGJxRkZsQmNzYmhEdjI3TzBWRU9kdmdPCkJnTDhZbUtUQWtFQXNJWGx1RGxnbUtrcUZQU2E4Q0JzeUhTSVhHbllhK1p0UUt3RVU1MUZ6dHdpTDgzRm1KVVkKV0RPUUJ2YUI4N2dGNUMwVVNYWHdNSkp0enN0N1p0cENnUUpCQU05RktVR0hjb2hRdzIzMnd0NjFnL1I1VENESwprdGdUSHBVbEVoVXE2K2hXbUg4SW55NzRhVnB3aDhIT0NOSS9tZEZpR1pCMUU0OXJ3UVJ3SHEwdG1lRUNRR0VuCmNNV3lIcTRtL05oSHdEYkZRZG9aK1NzVHZsKzBsUkR4Ry9pQktQaXZROG1Yc1ZkSFIvelRkRVBBek1rODBWRkMKVmxZUUtVQXlkMmxIcVFWMHZ3RUNRUURWRlJVTlJDWlFZK0JLS3hYMXpYNzdpTEJEQU9Ka0duOWNTSWN5eUFZUAppemFpN2NGdU53czVySUlZV3c2cGRxZUpEZDJkVWFYQlpuUmFGeHo3OHdTdwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ=="
JWT_PUBLIC_KEY="LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FDcmJNcW0xQ3dUYXFYenE1ZFFTY0JBTnczSApuSllhbEhKbnMzbHZ3TjV1VUdzV1Frc1gwUFpyTmQ3VUlSUGQ0WUZXQ1Fva08reXZ3U04rRGdpa3ZkU05PdXpNCnZlS0c5eGs5NittQUdQeUwzVTdKNW1NWFRHL2RDL2xodE5qNUtNa2VkYUtoenEwRUx2YWtEZU1Rdno4QVppNjQKNTN4OXpNZ2NjZGxDRGl1U0V3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=="

# class AuthenticationSetting(BaseModel):
#     authjwt_algorithm: str = settings.JWT_ALGORITHM
#     authjwt_decode_algorithms: List[str] = [settings.JWT_ALGORITHM]
#     authjwt_token_location: set = {'cookies', 'headers'}
#     authjwt_access_cookie_key: str = 'access_token'
#     authjwt_refresh_cookie_key: str = 'refresh_token'
#     authjwt_cookie_csrf_protect: bool = False
#     authjwt_public_key: str = base64.b64decode(
#         JWT_PUBLIC_KEY).decode('utf-8')
#     authjwt_private_key: str = base64.b64decode(
#         JWT_PRIVATE_KEY).decode('utf-8')


# @AuthJWT.load_config
# def get_config():
#     return AuthenticationSetting()

